### ISSUE TITLE
inclusion of curated list of phospho-SLiMs

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/MAVISp#150]
The current module ptm.function is not giving a specific match between a mutation at a PTM site and the existence of a phospho-regulated SLiM in ELM. It is reporting an annotation for 'possibly pathogenic' if any SLiM is found in correspondance of the PTM. To provide a more accurate annotation, I have been curating the phospho-regulated SLiM from ELM and the class of phospho-residues interested by it in a csv that can be used by mavisp.py. A first version aims to contain approximately 40 phospho-dependent SLiMs.

**Comment by mtiberti** [comment]
done in #151
