### ISSUE TITLE
Update internal dictionary with new cases

### ISSUE THREAD

**Issue by SimoneScrima** [ELELAB/MAVISp#249]
As per title

**Comment by mtiberti** [comment]
closing this as it is not relevant anymore, plus it has been updated by @elenapapaleo with 7f1f03151c42df9ecb7155301ae1ec0fd05b7e21

**Comment by mtiberti** [comment]
closing this as it is not relevant anymore, plus it has been updated by @elenapapaleo with https://github.com/ELELAB/MAVISp/commit/7f1f03151c42df9ecb7155301ae1ec0fd05b7e21
